### PR TITLE
[JEP-286] Local-Variable Type Inference tests

### PR DESCRIPTION
**Pull request by mjurc**
* Adding tests for JEP-286 Local-Variable Type Inference 

Requires #7

### CODE REVIEW

**Comment by msve** [comment]
BTW don't forget to add JDK11 tests for var which is extended to be allowed in lambda expressions too, e.g. `(var x, var y) -> x.process(y)`.

**Comment by mjurc** [comment]
@msve tests added, JEP-323 tests added in #10

**Comment by rsvoboda** [comment]
@mjurc resolve conflicts please

**Comment by mjurc** [comment]
@msve @rsvoboda Fixed'n'rebased :+1:

**Pull request merged**
